# Generated by Django 6.0.1 on 2026-01-17 20:39

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500)),
                ('answer_type', models.CharField(choices=[('SHORT_TEXT', 'Short Text'), ('LONG_TEXT', 'Long Text'), ('PHONE_NUMBER', 'Phone Number'), ('EMAIL', 'Email'), ('TIMESTAMP', 'Timestamp'), ('LINK', 'Link'), ('INTEGER', 'Integer'), ('DECIMAL', 'Decimal'), ('POINT', 'Point'), ('LINE', 'Line'), ('POLYGON', 'Polygon'), ('SINGLE_CHOICE', 'Single Choice'), ('MULTI_CHOICE', 'Multiple Choice'), ('IMAGE', 'Image'), ('DOCUMENT', 'Document'), ('VIDEO', 'Video'), ('AUDIO', 'Audio')], default='SHORT_TEXT', max_length=50)),
                ('required_text', models.CharField(blank=True, max_length=200, null=True)),
                ('options', models.TextField(blank=True, help_text='Comma-separated options for CHOICE type questions', null=True)),
                ('placeholder', models.CharField(blank=True, max_length=200, null=True)),
                ('hint', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FilterLogic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mapping', models.TextField(help_text="Mapping in the format 'source_value1:choice1,choice2;source_value2:choice3,choice4'")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_choice_logics', to='forms.question')),
                ('source_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filtered_by', to='forms.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('long_text_answer', models.TextField(blank=True, null=True)),
                ('short_text_answer', models.CharField(blank=True, max_length=500, null=True)),
                ('link_answer', models.URLField(blank=True, null=True)),
                ('phone_number_answer', models.CharField(blank=True, max_length=20, null=True)),
                ('email_answer', models.EmailField(blank=True, max_length=254, null=True)),
                ('timestamp_answer', models.DateTimeField(blank=True, null=True)),
                ('integer_answer', models.IntegerField(blank=True, null=True)),
                ('decimal_answer', models.DecimalField(blank=True, decimal_places=6, max_digits=100, null=True)),
                ('single_choice_answer', models.CharField(blank=True, max_length=200, null=True)),
                ('multi_choice_answer', models.TextField(blank=True, help_text='Comma-separated values for multiple choices', null=True)),
                ('line_answer', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('point_answer', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('polygon_answer', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('document_answer', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('image_answer', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('video_answer', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('audio_answer', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='forms.question')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='questionnaires', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='forms.questionnaire'),
        ),
        migrations.CreateModel(
            name='SkipLogic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_value', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skipped_by', to='forms.question')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skip_logics', to='forms.question')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fill_duration', models.DurationField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('enumerator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='forms.questionnaire')),
            ],
        ),
    ]
